name: 'Apple action - Prepare xcbeautify'
description: 'Apply xcbeautify to xcodebuild globally'
runs:
  using: 'composite'
  steps:
    - name: Prepare xcbeautify
      run: |
        APPLE_ACTION_XCODEBUILD_COMMAND+='
          #!/bin/zsh -e
          export BEAUTIFY=0
          export BEAUTIFY_OPTION="(-create-xcframework|-exportArchive|-archivePath|-configuration|-destination)"
          for OPTION in "${@:1}"
          do
            if [[ $OPTION =~ $BEAUTIFY_OPTION ]]; then
              export BEAUTIFY=1
              break
            fi
          done
        '
        APPLE_ACTION_XCODEBUILD_PIPE+='([[ $BEAUTIFY == 1 ]] && xcbeautify && exit ${PIPESTATUS[0]} || cat)'
        echo $APPLE_ACTION_XCODEBUILD_COMMAND >> apple_action_xcodebuild_command
        chmod 755 apple_action_xcodebuild_command
        echo $APPLE_ACTION_XCODEBUILD_PIPE >> apple_action_xcodebuild_pipe
        echo '
          #!/bin/zsh -e
          export PATH=$(echo $PATH | sed s!$(dirname $(readlink -f $0)):!!g)
          . apple_action_xcodebuild_command
          xcodebuild "$@" $(cat apple_action_xcodebuild_option) | $(cat apple_action_xcodebuild_pipe)
        ' > xcodebuild
        chmod 755 xcodebuild
        echo $(dirname $(readlink -f xcodebuild)) >> $GITHUB_PATH
      shell: bash
